name: publish

on:
  release:
    types:
      - published

concurrency: publish
jobs:
  setversion:
    name: Set version (ESLINT-CONFIG)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update package.json version number
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq '.version = ${{  toJson(github.event.release.tag_name) }}' package.json > package.tmp && mv package.tmp package.json

      - name: Push updated build number
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit . -m "Update build version [skip ci]"
          git push origin
