name: publish

on:
  release:
    types:
      - released

concurrency: publish
jobs:
  publish:
    name: Publish to npm (ESLINT-CONFIG)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: Update package.json version number
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq '.version = ${{  toJson(github.event.release.tag_name) }}' package.json > package.tmp && mv package.tmp package.json

      - name: Push updated build number
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit . -m "Update build version [skip ci]"
          git push origin

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - run: yarn install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
